name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: get-version
        run: |
          echo "::set-output name=version::$(cat setup.cfg | grep version | awk '{split($0,a," "); print "v"a[3]}')\n"
      - name: fetch-latest-release
        uses: thebritican/fetch-latest-release@v2.0.0
      - name: List versions
        run: |
          echo "Version ${{ steps.get-verison.output.version }}"
          echo "Tag ${{ steps.fetch-latest-release.outputs.tag_name }}"
      - name: Tag Commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.VERSION }}
        if: ${{ steps.fetch_latest_release.outputs.tag_name < env.VERSION }}
      - name: Create a Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            dist/*
        if: ${{ steps.fetch_latest_release.outputs.tag_name < env.VERSION }}
